coverage:
  status:
    patch:
      default:
        target: 70

ignore:
  - "cloud/*/types"
  - "pkg/buldinfo"
    # TODO re-enable coverage checking for the following cmd files
  - "/cmd/create*"
  - "/cmd/delete*"
  - "/cmd/export*"
  - "/cmd/get*"
  - "/cmd/upgrade*"
  - "/cmd/root*"
  - "/cmd/version*"
